ERROR 2021-09-18 20:17:04,133 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/Virtualenvs/LuffyBackend/LuffyBackend/apps/userinfo/views.py", line 11, in add
    logging.info()
TypeError: info() missing 1 required positional argument: 'msg'
ERROR 2021-09-18 20:17:04,134 basehttp 154 "GET / HTTP/1.1" 500 66082
CRITICAL 2021-09-22 19:39:36,186 exception 19 (1146, "Table 'luffycity.luffy_banner' doesn't exist")
ERROR 2021-09-22 19:39:36,263 log 228 Internal Server Error: /api/v1/home/banner/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2021-09-22 19:39:36,264 basehttp 154 "GET /api/v1/home/banner/ HTTP/1.1" 500 84703
CRITICAL 2021-09-22 19:40:24,535 exception 19 (1146, "Table 'luffycity.luffy_banner' doesn't exist")
ERROR 2021-09-28 19:51:54,303 log 228 Internal Server Error: /api/v1/user/login//login/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/creambluea/Virtualenvs/LuffyCity/LuffyBackend/LuffyBackend/apps/userinfo/views.py", line 19, in login
    if ser.is_valid(raise_exception=True):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'username': [ErrorDetail(string='请确保这个字段至少包含 4 个字符。', code='min_length')]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/creambluea/Virtualenvs/LuffyCity/LuffyBackend/LuffyBackend/utils/exception.py", line 17, in exception_handler
    response = Response({'code': 998, 'msg': response.data['detail']})
KeyError: 'detail'
ERROR 2021-09-28 19:51:54,306 basehttp 154 "POST /api/v1/user/login//login/ HTTP/1.1" 500 99473
ERROR 2021-09-28 19:53:45,927 log 228 Internal Server Error: /api/v1/user/login/login/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/creambluea/Virtualenvs/LuffyCity/LuffyBackend/LuffyBackend/apps/userinfo/views.py", line 19, in login
    if ser.is_valid(raise_exception=True):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'username': [ErrorDetail(string='请确保这个字段至少包含 4 个字符。', code='min_length')]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/creambluea/Virtualenvs/LuffyCity/LuffyBackend/LuffyBackend/utils/exception.py", line 17, in exception_handler
    response = Response({'code': 998, 'msg': response.data['detail']})
KeyError: 'detail'
ERROR 2021-09-28 19:53:45,928 basehttp 154 "POST /api/v1/user/login/login/ HTTP/1.1" 500 99454
ERROR 2021-09-28 19:54:50,855 log 228 Internal Server Error: /api/v1/user/login/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/creambluea/Virtualenvs/LuffyCity/LuffyBackend/LuffyBackend/apps/userinfo/views.py", line 19, in login
    if ser.is_valid(raise_exception=True):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'username': [ErrorDetail(string='请确保这个字段至少包含 4 个字符。', code='min_length')]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/creambluea/Virtualenvs/LuffyCity/LuffyBackend/LuffyBackend/utils/exception.py", line 17, in exception_handler
    response = Response({'code': 998, 'msg': response.data['detail']})
KeyError: 'detail'
ERROR 2021-09-28 19:54:50,856 basehttp 154 "POST /api/v1/user/login/ HTTP/1.1" 500 99340
CRITICAL 2021-09-28 19:56:42,639 exception 24 {'username': [ErrorDetail(string='请确保这个字段至少包含 4 个字符。', code='min_length')]}
CRITICAL 2021-09-28 19:58:10,691 exception 24 'ValidationError' object has no attribute 'username'
CRITICAL 2021-09-28 19:58:48,968 exception 24 'ValidationError' object has no attribute 'username'
CRITICAL 2021-09-28 20:01:30,437 exception 24 'ValidationError' object has no attribute 'username'
CRITICAL 2021-09-28 20:03:35,190 exception 24 'ValidationError' object has no attribute 'username'
CRITICAL 2021-09-28 20:10:37,462 exception 24 'ValidationError' object has no attribute 'username'
CRITICAL 2021-09-28 21:02:13,994 exception 24 手机号不存在
CRITICAL 2021-09-28 23:58:52,373 exception 24 match() missing 1 required positional argument: 'string'
CRITICAL 2021-09-29 00:12:23,486 exception 24 match() missing 1 required positional argument: 'string'
CRITICAL 2021-09-29 00:15:58,226 exception 24 match() missing 1 required positional argument: 'string'
CRITICAL 2021-09-29 00:16:44,465 exception 24 match() missing 1 required positional argument: 'string'
CRITICAL 2021-09-29 00:17:13,664 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 00:18:38,015 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 08:25:32,369 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 08:45:56,917 exception 24 手机号不存在
CRITICAL 2021-09-29 08:46:47,030 exception 24 {'username': [ErrorDetail(string='该字段是必填项。', code='required')], 'password': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-09-29 08:49:06,391 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 08:49:30,529 exception 24 方法 “POST” 不被允许。
ERROR 2021-09-29 08:49:37,971 log 228 Internal Server Error: /api/v1/user/send_sms/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.exceptions.APIException'>`
ERROR 2021-09-29 08:49:37,972 basehttp 154 "GET /api/v1/user/send_sms/ HTTP/1.1" 500 82717
CRITICAL 2021-09-29 08:50:07,567 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 17:04:58,970 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 17:15:36,746 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 17:16:24,513 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 17:16:35,297 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 17:16:36,048 exception 24 请求超过了限速。 Expected available in 60 seconds.
CRITICAL 2021-09-29 17:17:26,308 exception 24 'Settings' object has no attribute 'CACHE_SMS'
CRITICAL 2021-09-29 17:17:53,730 exception 24 请求超过了限速。 Expected available in 33 seconds.
CRITICAL 2021-09-29 17:18:07,456 exception 24 'Settings' object has no attribute 'CACHE_SMS'
ERROR 2021-09-29 17:26:01,199 log 228 Internal Server Error: /api/v1/user/sms/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.exceptions.APIException'>`
ERROR 2021-09-29 17:26:01,200 basehttp 154 "GET /api/v1/user/sms/?mobile=18658025230 HTTP/1.1" 500 83396
ERROR 2021-09-29 18:39:45,060 log 228 Internal Server Error: /api/v1/user/sms/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.exceptions.APIException'>`
ERROR 2021-09-29 18:41:25,084 log 228 Internal Server Error: /api/v1/user/sms/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.exceptions.APIException'>`
ERROR 2021-09-29 18:41:25,085 basehttp 154 "GET /api/v1/user/sms/?mobile=18658025230 HTTP/1.1" 500 83396
CRITICAL 2021-09-29 18:41:48,687 exception 24 短信发送失败
CRITICAL 2021-09-29 18:42:40,264 exception 24 短信发送失败
CRITICAL 2021-09-29 19:38:59,662 exception 24 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:39:46,299 exception 24 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:41:55,144 exception 24 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:49:43,700 exception 23 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:51:32,594 exception 23 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:51:58,245 exception 23 'dict' object has no attribute 'code'
CRITICAL 2021-09-29 19:52:52,587 exception 23 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:57:21,830 exception 23 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 19:58:12,057 exception 23 {'non_field_errors': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 20:51:36,735 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 20:51:57,659 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 20:51:59,259 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 20:52:47,247 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-29 20:53:20,624 exception 23 '111111'
CRITICAL 2021-09-29 20:54:21,815 exception 23 '111111'
CRITICAL 2021-09-29 20:55:54,750 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-29 20:56:10,032 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-09-29 20:59:33,327 exception 23 {'username': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-09-29 21:00:59,965 exception 23 {'username': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-09-29 21:01:00,654 exception 23 {'username': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-09-29 21:01:57,924 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-29 21:02:56,775 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-09-29 21:03:08,894 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-29 21:03:50,822 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-29 21:06:18,195 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-09-29 21:08:45,830 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-29 21:09:35,582 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-09-29 21:10:03,752 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-09-30 00:08:58,219 exception 23 {'non_field_errors': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 00:11:26,843 exception 23 {'detail': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 00:12:28,772 exception 23 {'detail': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 15:29:57,167 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:33:46,831 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:34:28,359 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:34:41,936 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:36:07,957 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:37:56,672 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:38:03,414 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:57:12,950 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:58:51,521 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:59:19,836 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 15:59:49,648 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:02:20,742 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:04:31,555 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:04:36,796 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:05:06,095 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:06:48,970 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:07:18,852 exception 23 方法 “GET” 不被允许。
CRITICAL 2021-09-30 16:08:35,034 exception 23 手机号不存在
CRITICAL 2021-09-30 16:08:51,366 exception 23 手机号不存在
CRITICAL 2021-09-30 16:09:20,418 exception 23 手机号不存在
CRITICAL 2021-09-30 16:12:19,113 exception 23 手机号不存在
CRITICAL 2021-09-30 16:12:21,884 exception 23 手机号不存在
CRITICAL 2021-09-30 16:13:15,815 exception 23 手机号不存在
CRITICAL 2021-09-30 16:14:11,963 exception 23 手机号不存在
CRITICAL 2021-09-30 16:15:41,238 exception 23 手机号不存在
CRITICAL 2021-09-30 16:17:53,378 exception 23 手机号不存在
CRITICAL 2021-09-30 16:18:54,358 exception 23 手机号不存在
CRITICAL 2021-09-30 16:19:15,360 exception 23 手机号不存在
CRITICAL 2021-09-30 16:23:52,930 exception 23 手机号不存在
CRITICAL 2021-09-30 16:24:46,558 exception 23 手机号不存在
CRITICAL 2021-09-30 16:48:09,956 exception 23 name 'APPID' is not defined
CRITICAL 2021-09-30 16:53:33,540 exception 23 name 'APPID' is not defined
CRITICAL 2021-09-30 17:07:45,661 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 17:16:25,259 exception 23 {'detail': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 17:16:33,785 exception 23 {'detail': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 17:18:57,253 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 19:03:39,297 exception 23 set() got an unexpected keyword argument 'code'
CRITICAL 2021-09-30 19:06:16,317 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 19:06:16,515 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 19:06:16,611 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 19:06:35,402 exception 23 set() got an unexpected keyword argument 'cache_code'
CRITICAL 2021-09-30 19:18:15,635 exception 23 'APIResponse' object has no attribute 'username'
CRITICAL 2021-09-30 19:19:07,179 exception 23 type object argument after ** must be a mapping, not UserInfo
CRITICAL 2021-09-30 19:19:33,666 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-30 19:19:57,325 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-30 19:20:02,813 exception 23 type object argument after ** must be a mapping, not str
CRITICAL 2021-09-30 19:20:22,432 exception 23 'APIResponse' object has no attribute 'username'
CRITICAL 2021-09-30 19:23:25,094 exception 23 'APIResponse' object has no attribute 'username'
CRITICAL 2021-09-30 19:48:00,993 exception 23 HTTP status code must be an integer.
CRITICAL 2021-09-30 19:50:49,286 exception 23 'UserInfo' object has no attribute 'msg'
CRITICAL 2021-09-30 19:52:28,352 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 19:53:44,211 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 20:01:17,084 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-09-30 20:14:36,032 exception 23 {'detail': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 20:16:19,925 exception 23 {'detail': [ErrorDetail(string='用户名或密码错误', code='invalid')]}
CRITICAL 2021-09-30 20:24:56,125 exception 23 请求超过了限速。 Expected available in 16 seconds.
CRITICAL 2021-09-30 20:25:09,543 exception 23 请求超过了限速。 Expected available in 3 seconds.
CRITICAL 2021-09-30 20:26:45,935 exception 23 请求超过了限速。 Expected available in 16 seconds.
CRITICAL 2021-09-30 20:27:17,499 exception 23 请求超过了限速。 Expected available in 47 seconds.
CRITICAL 2021-09-30 20:53:50,275 exception 23 短信发送失败
CRITICAL 2021-10-01 14:21:04,871 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-01 14:21:22,099 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-01 14:32:31,098 exception 23 短信发送失败
CRITICAL 2021-10-01 14:36:38,906 exception 23 短信发送失败
CRITICAL 2021-10-01 14:38:22,967 exception 23 短信发送失败
CRITICAL 2021-10-01 15:15:10,824 exception 23 手机号不存在
CRITICAL 2021-10-01 15:15:20,789 exception 23 手机号不存在
CRITICAL 2021-10-01 15:18:06,721 exception 23 手机号不存在
CRITICAL 2021-10-01 15:29:35,221 exception 23 手机号不存在
CRITICAL 2021-10-01 15:30:11,834 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:32:27,664 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:42:03,036 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:44:19,702 exception 23 手机号不存在
CRITICAL 2021-10-01 15:44:22,540 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:45:04,059 exception 23 手机号不存在
CRITICAL 2021-10-01 15:45:10,908 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:45:59,473 exception 23 手机号不存在
CRITICAL 2021-10-01 15:46:04,052 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:53:08,033 exception 23 手机号不存在
CRITICAL 2021-10-01 15:53:13,172 exception 23 手机号不存在
CRITICAL 2021-10-01 15:53:17,787 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:54:44,696 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:57:33,192 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:57:33,412 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:58:02,513 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-01 15:58:02,634 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 08:43:12,658 exception 23 手机号不存在
ERROR 2021-10-02 08:43:16,341 sms 25 18958546318手机号，发送短信失败，错误信息是[Errno 8] nodename nor servname provided, or not known
CRITICAL 2021-10-02 08:43:16,344 exception 23 local variable 'result' referenced before assignment
CRITICAL 2021-10-02 08:45:22,824 exception 23 手机号不存在
CRITICAL 2021-10-02 08:45:57,103 exception 23 手机号不存在
CRITICAL 2021-10-02 08:46:12,965 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 08:47:19,451 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 08:48:24,999 exception 23 'dict' object has no attribute 'code'
CRITICAL 2021-10-02 08:48:43,730 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 08:52:24,472 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 08:53:34,500 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 08:54:42,936 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 09:00:53,872 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-10-02 09:03:41,824 exception 23 {'sms': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 09:04:35,836 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 09:05:36,451 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-02 09:06:00,494 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-02 09:06:01,305 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-02 09:12:18,464 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 09:12:29,954 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 09:13:22,414 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-02 09:14:03,786 exception 23 {'code': [ErrorDetail(string='该字段是必填项。', code='required')]}
CRITICAL 2021-10-04 20:08:48,129 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')], 'code': [ErrorDetail(string='请确保这个字段至少包含 6 个字符。', code='min_length')]}
CRITICAL 2021-10-04 20:09:01,540 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')], 'code': [ErrorDetail(string='请确保这个字段至少包含 6 个字符。', code='min_length')]}
CRITICAL 2021-10-04 20:09:30,545 exception 23 {'mobile': [ErrorDetail(string='具有 mobile 的 用户表 已存在。', code='unique')]}
CRITICAL 2021-10-09 16:58:55,906 exception 23 手机号不存在
CRITICAL 2021-10-09 16:59:12,373 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-09 17:00:03,562 exception 23 The given username must be set
CRITICAL 2021-10-09 17:00:51,845 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-09 17:00:53,547 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-09 17:01:26,445 exception 23 {'detail': [ErrorDetail(string='验证码错误', code='invalid')]}
CRITICAL 2021-10-09 17:04:28,629 exception 23 The given username must be set
CRITICAL 2021-10-09 17:05:04,666 exception 23 The given username must be set
CRITICAL 2021-10-09 17:06:15,002 exception 23 The given username must be set
CRITICAL 2021-10-09 17:08:59,242 exception 23 'builtin_function_or_method' object does not support item assignment
CRITICAL 2021-10-09 17:09:19,732 exception 23 The given username must be set
CRITICAL 2021-10-09 17:09:19,893 exception 23 The given username must be set
CRITICAL 2021-10-09 17:10:28,594 exception 23 The given username must be set
CRITICAL 2021-10-09 17:10:28,728 exception 23 The given username must be set
CRITICAL 2021-10-09 17:10:29,493 exception 23 The given username must be set
CRITICAL 2021-10-09 17:10:43,734 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:10,056 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:10,185 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:10,340 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:41,308 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:42,792 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:42,993 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:43,137 exception 23 The given username must be set
CRITICAL 2021-10-09 17:12:43,369 exception 23 The given username must be set
CRITICAL 2021-10-09 18:27:47,279 exception 23 The given username must be set
CRITICAL 2021-10-09 18:32:58,724 exception 23 The given username must be set
CRITICAL 2021-10-09 18:32:58,809 exception 23 The given username must be set
CRITICAL 2021-10-09 18:37:27,390 exception 23 setattr expected 3 arguments, got 0
CRITICAL 2021-10-09 18:37:56,277 exception 23 setattr expected 3 arguments, got 0
CRITICAL 2021-10-09 18:38:00,419 exception 23 The given username must be set
CRITICAL 2021-10-09 18:40:10,416 exception 23 The given username must be set
CRITICAL 2021-10-09 18:40:15,763 exception 23 The given username must be set
CRITICAL 2021-10-09 18:40:41,832 exception 23 The given username must be set
CRITICAL 2021-10-09 18:40:46,321 exception 23 The given username must be set
CRITICAL 2021-10-09 18:42:44,446 exception 23 The given username must be set
CRITICAL 2021-10-09 18:42:49,602 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:00,088 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:00,270 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:00,648 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:35,429 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:35,595 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:35,761 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:35,972 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:48,270 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:48,399 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:48,520 exception 23 The given username must be set
CRITICAL 2021-10-09 18:43:48,682 exception 23 The given username must be set
CRITICAL 2021-10-09 18:44:35,399 exception 23 The given username must be set
CRITICAL 2021-10-09 18:44:35,570 exception 23 The given username must be set
CRITICAL 2021-10-09 18:44:36,145 exception 23 The given username must be set
CRITICAL 2021-10-09 18:45:25,058 exception 23 手机号不存在
CRITICAL 2021-10-10 16:45:59,347 exception 23 'Teacher' object is not iterable
CRITICAL 2021-10-10 16:46:03,649 exception 23 'Teacher' object is not iterable
CRITICAL 2021-10-10 16:46:29,766 exception 23 'Teacher' object is not iterable
ERROR 2021-10-10 16:46:46,913 log 228 Internal Server Error: /api/v1/course/actual/
Traceback (most recent call last):
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/renderers.py", line 702, in get_context
    'filter_form': self.get_filter_form(data, view, request),
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/rest_framework/renderers.py", line 634, in get_filter_form
    html = backend().to_html(request, queryset, view)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 103, in to_html
    template = loader.get_template(self.template)
  File "/Users/creambluea/.virtualenvs/Luffy/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: django_filters/rest_framework/form.html
ERROR 2021-10-10 16:46:46,915 basehttp 154 "GET /api/v1/course/actual/ HTTP/1.1" 500 116505
CRITICAL 2021-10-10 17:22:14,912 exception 23 无效页面。
CRITICAL 2021-10-10 17:22:17,487 exception 23 无效页面。
CRITICAL 2021-10-10 18:06:39,324 exception 23 无效页面。
CRITICAL 2021-10-10 18:12:49,671 exception 23 无效页面。
CRITICAL 2021-10-10 18:12:59,120 exception 23 无效页面。
CRITICAL 2021-10-10 18:13:55,469 exception 23 无效页面。
CRITICAL 2021-10-10 18:14:29,678 exception 23 无效页面。
CRITICAL 2021-10-10 18:21:47,904 exception 23 无效页面。
CRITICAL 2021-10-10 18:21:49,744 exception 23 无效页面。
CRITICAL 2021-10-10 18:21:51,650 exception 23 无效页面。
CRITICAL 2021-10-10 18:23:13,497 exception 23 无效页面。
CRITICAL 2021-10-10 18:23:15,308 exception 23 无效页面。
CRITICAL 2021-10-10 18:23:19,049 exception 23 无效页面。
CRITICAL 2021-10-10 18:24:42,704 exception 23 无效页面。
CRITICAL 2021-10-10 18:24:44,318 exception 23 无效页面。
CRITICAL 2021-10-10 18:24:45,951 exception 23 无效页面。
CRITICAL 2021-10-10 18:45:18,090 exception 23 无效页面。
CRITICAL 2021-10-10 18:48:07,228 exception 23 无效页面。
